defaults: # for loading the default.yaml config
  - task: panoptic #???

  - visualization: default
  - lr_scheduler: exponential
  - training: pointgroup #default
#
  - debugging: default
  - models: panoptic/pointgroup #???
  - data: panoptic/s3disfused-sparseconv #???
  - sota # Contains current SOTA results on different datasets (extracted from papers !).
#  - hydra/job_logging: custom
  - hydra/output: custom  # add the support for user-defined experiment folder (where to save the experiment files)


job_name: custom_folder # prefix name for saving the experiment file.
model_name: PointGroup-PAPER  #??? # Name of the specific model to load
update_lr_scheduler_on: "on_epoch" # ["on_epoch", "on_num_batch", "on_num_sample"]
selection_stage: ""
pretty_print: False
eval_frequency: 1

tracker_options: # Extra options for the tracker
  full_res: False
  make_submission: False
  track_boxes: False