defaults: 
  - visualization: eval

num_workers: 0
batch_size: 1
cuda: 0
weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/scratch2/torch-points3d/outputs/pointnet_fold4_v2" # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: pointnet2NPM3D
precompute_multi_scale: True # Compute multiscate features on cpu for faster training / inference
enable_dropout: False
voting_runs: 1

data: 
  # number, e.g. 3 OR ply path, e.g. "/cluster/work/igp_psr/yuayue/RA/WP1/check_jan12/TP3D_PanopticSeg/data/npm3dfused/raw/Paris.ply"
  # fold: ["/cluster/work/igp_psr/yuayue/RA/WP1/check_jan12/TP3D_PanopticSeg/data/npm3dfused/raw/Lille1_1.ply"]
  # for italy dataset change the path here
  fold: 4
  
tracker_options: # Extra options for the tracker
  full_res: True
  make_submission: True
  ply_output: "vote1regular.ply"

hydra:
  run:
    dir: ${checkpoint_dir}/eval/${now:%Y-%m-%d_%H-%M-%S}


